### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by SlimeDog** [I2000C/NewAmazingLuckyBlocks#2]
Configuration:
- Ability to disable update checks.

Commands (executable from console or in-game):
- alb reload
- alb give <player> <n>

Permissions:
- amazinglb.admin = all permissions
- amazinglb.give = give a player a lucky block (or more than one, see above)
- amazinglb.place = place a lucky block
- amazinglb.use = use (ie., break) a lucky block

Localization support :: lang.yml:
- Specification of in-game prefix :: default = "[AmazingLuckyBlocks]"

Outcomes specification:
- List of outcomes
- Probability of each outcome (sum = 100)

I assume that breaking a lucky block produces a probabilistic outcome (I cannot test this, since I am waiting for 1.13.2 support).

**Comment by I2000C** [comment]
Interesting feature request. I will add the option to enable/disable the update checker, the "/alb give" command with its permissions and the in-game prefix configuration in the next updates. 

For the outcomes, I will try to make a probability system (At the moment, they are chosen randomly) that will be configurable.

To finish, I am having some problems in order to add 1.13.x support, but I believe this will be soon fixed.

**Comment by SlimeDog** [comment]
Until outcomes are public: It would be nice to have a list, so we can tell players what outcomes are possible.

Once outcomes are public: It would be nice to be able to add outcomes. Blocks, entities (with enhanced capabilities), items (with enchantments and custom names), structures (with WE support), etc.

**Comment by I2000C** [comment]
I agree you. In the future I will try to make it possible.
For the moment, I will add a list of the outcomes that are possible right now in the plugin webpage.

**Comment by SlimeDog** [comment]
(Moved to #7)

**Comment by SlimeDog** [comment]
Issues resolved except for outcome control, separated per ^^^
